services:
  app:
    container_name: slsw-next-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Se tiver variáveis de ambiente, descomente abaixo:
    # env_file:
    #   - .env